name: mpytc
dependencies:
  - python=3.7
  - jupyter
  - notebook
  - tqdm
  - pytorch::pytorch==1.7.1
  - pytorch::torchtext
  - pytorch::torchvision
  - fastai::fastai==2.1.8  # https://forums.fast.ai/t/part1-2020-02-production-found-at-least-two-devices-cuda-0-and-cpu/87253/18
  - pip
  - pip:
    - matplotlib
    - nltk
    - pycocotools
    - torchviz
    - networkx
    - sentencepiece
    - transformers
    - cython  # needed for pycocotools
    - atari-py
    - gym
    - autoPyTorch
    - configspace
    - git+https://github.com/shukon/HpBandSter.git
    - optuna
    - captum
    - Pillow<8.3.0  # https://forums.fast.ai/t/runtimeerror-could-not-infer-dtype-of-pilimage/89697
