name: mpytc
dependencies:
  - python=3.7
  - jupyter==1.0.0
  - notebook
  - tqdm=4.43.0
  - pytorch::pytorch==1.4.0
  - pytorch::torchtext==0.5.0
  - pytorch::torchvision==0.5.0
  - pip
  - pip:
    - matplotlib==3.1.2
    - torchviz==0.0.1
    - networkx==2.4
    - sentencepiece
    - transformers
    - nltk
    - pycocotools
    - cython  # needed for pycocotools